!!python/object:argparse.Namespace
arch: resnet18
aug_type: amp_gm_v1
batch_size: 256
data: ./datasets
dataset_name: cifar10
device: !!python/object/apply:torch.device
- cuda
disable_cuda: false
epochs: 1000
fp16_precision: false
gpu_index: 0
log_every_n_steps: 100
lr: 0.0003
max_coeff_amp: 0.5
max_coeff_phs: 0.5
n_views: 2
out_dim: 128
prob_transform: 0.5
projectname: simclr_combineA_seed229
seed: 229
temperature: 0.07
use_fftclr: 1
use_simclr: 1
variantB: 0
warmup_epoch: 10
weight_decay: 0.0001
workers: 3
